### ISSUE TITLE
missing layouts on branch master

### ISSUE THREAD

**Issue by edisukakoding** [InfyOmLabs/stisla-templates#5]
please add it soon because if you use a lower version it is not supported by laravel 9

**Comment by mitulgolakiya** [comment]
@edisukakoding layouts are not missing. It's removed purposefully. Because if you check the latest version. Now this package has a dependency of https://github.com/InfyOmLabs/laravel-ui-stisla

Since laravel scaffolding is moved to laravel-ui. This package has now its own package laravel-ui-stisla which handles scaffolding and layouts are moved to that package.

Refer to new release notes and new installation steps on our website and it should work.
